### PR TITLE
fsp-usb support   wenmt to a pc to add it

### PR DESCRIPTION
**Pull request by fennectech**

### CODE REVIEW

**Comment by fennectech** [comment]
best hold off on merging this until we know weather it will be sysmodule or merged into atmo

**Comment by friedkeenan** [comment]
Isn't fsp-usb a kip? Did you test this?

**Comment by fennectech** [comment]
no. FSP_USB is not a kip. i pulled it fom my working config file ive been using for debugging the driver.   fsp-usb is in in progress usb mass storage driver (that may get intigrated into atmosphere instaid of its own sysmodule) with the aim to allow flash drives to work on the switch.

**Comment by nicholemattera** [comment]
FSP_USB can now add a 'toolbox.json' file if/when they want to support Kosmos Toolbox.

**Pull request closed without merging**
